# permissions for end users to edit externalvisitsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalvisitset-editor-role
rules:
- apiGroups:
  - apps.zt1
  resources:
  - externalvisitsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.zt1
  resources:
  - externalvisitsets/status
  verbs:
  - get
