# permissions for end users to view externalvisitsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalvisitset-viewer-role
rules:
- apiGroups:
  - apps.zt1
  resources:
  - externalvisitsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.zt1
  resources:
  - externalvisitsets/status
  verbs:
  - get
